- id: '1699583739347'
  alias: 'Switch: Bedroom All Lights Off'
  description: Long Press Off Button
  trigger:
    - device_id: 3f330cd2e69e8ee831d5c5f0ab4bc433
      domain: hue
      platform: device
      type: long_press
      subtype: 4
      unique_id: 96d604ca-c2a4-4d4f-84f2-dbc6728ae2ae
    - device_id: c0fe949098f7ff63239d22535cf3240a
      domain: hue
      platform: device
      type: long_press
      subtype: 4
      unique_id: bce336b1-6bc2-4a46-bdd5-1c7bf7bbfd13
  condition: []
  action:
    - service: light.turn_off
    data:
      transition: 5
      target:
      entity_id: light.all_lights
  mode: single
- id: '1699583900858'
  alias: 'Switch: Bedroom All Lights Lights On'
  description: Long Press On Button
  trigger:
    - device_id: 3f330cd2e69e8ee831d5c5f0ab4bc433
      domain: hue
      platform: device
      type: long_press
      subtype: 1
      unique_id: b21ca135-d892-465c-91f0-934426a4a5c9
  condition: []
  action:
    - service: light.turn_on
      data:
        transition: 60
        color_temp: 228
        brightness_pct: 100
      target:
      entity_id: light.all_lights
  mode: single
- id: '1699584786811'
  alias: 'Switch: Bedroom Lights On'
  description: Short Press On Button
  trigger:
    - device_id: 3f330cd2e69e8ee831d5c5f0ab4bc433
      domain: hue
      platform: device
      type: short_release
      subtype: 1
      unique_id: b21ca135-d892-465c-91f0-934426a4a5c9
  condition: []
  action:
    - service: light.turn_on
      data:
        transition: 5
        color_temp: 234
        brightness_pct: 100
      target:
        device_id:
          - 3e85e140da7932a78fa8c0c855488192
          - 0df99c2f064682cb887bdbc6004b11ff
          - 4f72c3af81e2dbfec9b42c8daa27bff6
          - 10bd54ec1321964b8f42513d95569fb1
          - e2863f42283465b7f5d3f51bdbf80ca2
          - 8fa0f75f077510dafcc4ba0cc5e02444
  mode: single
- id: '1699584906064'
  alias: 'Switch: Bedroom Lights Off'
  description: Short Press Off Button
  trigger:
    - device_id: 3f330cd2e69e8ee831d5c5f0ab4bc433
      domain: hue
      platform: device
      type: short_release
      subtype: 4
      unique_id: 96d604ca-c2a4-4d4f-84f2-dbc6728ae2ae
  condition: []
  action:
    - service: light.turn_off
      data:
        transition: 5
      target:
        device_id:
          - 3e85e140da7932a78fa8c0c855488192
          - 0df99c2f064682cb887bdbc6004b11ff
          - 4f72c3af81e2dbfec9b42c8daa27bff6
          - 10bd54ec1321964b8f42513d95569fb1
          - e2863f42283465b7f5d3f51bdbf80ca2
          - 8fa0f75f077510dafcc4ba0cc5e02444
  mode: single
- id: '1699590281953'
  alias: 'Switch: Downstairs Lights Off'
  description: Short Press Off Button
  trigger:
    - device_id: c0fe949098f7ff63239d22535cf3240a
      domain: hue
      platform: device
      type: short_release
      subtype: 4
      unique_id: bce336b1-6bc2-4a46-bdd5-1c7bf7bbfd13
  condition: []
  action:
    - service: light.turn_off
      data:
        transition: 5
      target:
        device_id:
          - ae9a7a6ecc1a78fb729248e254f52b32
          - 2fbfe2a1a69c726b59f2876e08c597f9
          - 04b3402eedc91e13a89c8d108bc7fd56
          - 1e2569baf7100aa8803bea93d7c70707
          - 4285466a8f1c5d3a42b2db310dff1f69
          - 303d1584166e2c7c7de70d806228e855
  mode: single
- id: '1699590566951'
  alias: 'Switch: Downstairs Lights On'
  description: Short Press On Button
  trigger:
    - device_id: c0fe949098f7ff63239d22535cf3240a
      domain: hue
      platform: device
      type: short_release
      subtype: 1
      unique_id: 28d403aa-6339-4a1e-a63f-7f0e98dbccf0
  condition: []
  action:
    - service: light.turn_on
      data:
        color_temp: 412
        brightness_pct: 100
        transition: 15
      target:
        device_id:
          - ae9a7a6ecc1a78fb729248e254f52b32
          - 2fbfe2a1a69c726b59f2876e08c597f9
          - 04b3402eedc91e13a89c8d108bc7fd56
          - 4285466a8f1c5d3a42b2db310dff1f69
          - 303d1584166e2c7c7de70d806228e855
          - 1e2569baf7100aa8803bea93d7c70707
  mode: single
- id: '1699732340926'
  alias: Frigidare Power Toggle
  description: ''
  trigger:
    - platform: state
      entity_id:
        - input_boolean.frigidaire_ac_button
  condition: []
  action:
    - service: script.frigidaire_climate_control_upstairs_power_toggle
      data: {}
  mode: single
- id: '1699732652226'
  alias: LG AC Power Toggle
  description: ''
  trigger:
    - platform: state
      entity_id:
        - input_boolean.lg_ac_button
  condition: []
  action:
    - service: script.lg_climate_control_upstairs_power_toggle
      data: {}
  mode: single
- id: '1707603165027'
  alias: Play Clock Sound on the Half-Hour
  description: Plays a clock sound every half-hour when the sun is up
  trigger:
    - platform: time_pattern
    minutes: '30'
  condition:
    - condition: state
      entity_id: sun.sun
      state: above_horizon
  action:
    - service: media_player.play_media
      target:
        entity_id: media_player.home
      data:
        media_content_id: media-source://media_source/local/antique-wood-chime-bell-ring.wav
        media_content_type: music
- id: '1709497089270'
  alias: Play Clock Sound on the Hour
  description: Plays a clock sound every hour when the sun is up and not playing frog
    sounds
  trigger:
  - platform: time_pattern
    minutes: '0'
  condition:
  - condition: state
    entity_id: sun.sun
    state: above_horizon
  - condition: state
    entity_id: input_boolean.frog_sounds_today
    state: 'off'
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.home
    data:
      media_content_id: media-source://media_source/local/antique-wood-chime-bell-ring.wav
      media_content_type: music
  mode: single
- id: '1710103968772'
  alias: Sync Sengled with Hue - Dynamic Palette
  description: Mimic Hue dynamic scene on Sengled lights
  trigger:
  - platform: template
    value_template: '{{ is_state_attr(''light.home'', ''dynamics'', ''true'')}}'
    enabled: true
  - platform: state
    entity_id:
    - input_boolean.theme_mode
    from:
    to: 'on'
  - platform: state
    entity_id:
    - binary_sensor.music_area_entertainment_configuration
    from:
    to: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id:
      - light.bed_light_strip_1
      - light.laundry_room_overhead_1
      brightness: '{{ state_attr(''light.media_room_overhead_light'', ''brightness'')}}'
      rgb_color: '{{ state_attr(''light.media_room_overhead_light'', ''rgb_color'')
        }}'
  - service: light.turn_on
    data:
      entity_id:
      - light.stairs_light_strip
      - light.kitchen_overhead_1
      - light.living_room_light
      brightness: '{{ state_attr(''light.stairs_overhead_light'', ''brightness'')
        }}'
      rgb_color: '{{ state_attr(''light.stairs_overhead_light'', ''rgb_color'') }}'
  - service: light.turn_on
    data:
      entity_id:
      - light.kitchen_overhead_2
      - light.laundry_room_overhead_2
      brightness: '{{ state_attr(''light.bedroom_overhead_light'', ''brightness'')
        }}'
      rgb_color: '{{ state_attr(''light.bedroom_overhead_light'', ''rgb_color'') }}'
  - service: light.turn_on
    data:
      entity_id:
      - light.dining_room_light
      - light.bed_light_strip_2
      brightness: '{{ state_attr(''light.floorlamp'', ''brightness'') }}'
      rgb_color: '{{ state_attr(''light.floorlamp'', ''rgb_color'') }}'
  mode: single
  max: 10
- id: '1710456631644'
  alias: Persistent Theme Lights
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.hue_groups_dynamic_scening
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: input_boolean.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.theme_mode
  mode: single
- id: '1710456739075'
  alias: Theme Is Running
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.theme_mode
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id:
      - input_boolean.regular_lights
  mode: single
- id: '1710456822979'
  alias: Theme is off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.theme_mode
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: input_boolean.turn_on
    target:
      entity_id:
      - input_boolean.regular_lights
    data: {}
  mode: single
- id: '1710543988869'
  alias: Adjust Indoor Lighting Based on Cloud Coverage
  description: Dynamically adjusts the indoor light brightness based on cloud coverage
    percentage during the day.
  trigger:
  - platform: state
    entity_id: sensor.openweathermap_cloud_coverage
  condition:
  - condition: state
    entity_id: sun.sun
    state: above_horizon
  action:
  - service: input_number.set_value
    target:
      entity_id: input_number.home_light_brightness
    data_template:
      value: "{% set baseline_brightness = 50 %} {% set max_adjustment = 100 %} {%
        set cloud_coverage = states('sensor.openweathermap_cloud_coverage') | float(default=0)
        %}\n{% if cloud_coverage is none %}\n  {% set cloud_coverage = 0 %}\n{% endif
        %}\n{% set calculated_brightness = baseline_brightness + ((cloud_coverage
        / 100) * (max_adjustment - baseline_brightness)) %} {% if calculated_brightness
        > max_adjustment %}\n  {% set calculated_brightness = max_adjustment %}\n{%
        elif calculated_brightness < 0 %}\n  {% set calculated_brightness = 0 %}\n{%
        endif %}\n{{ calculated_brightness }}\n"
  mode: single
- id: '1710640274265'
  alias: Bedroom AC Control
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.bedroom_motion_sensor_temperature
    above: 75
  - platform: numeric_state
    entity_id: sensor.bedroom_motion_sensor_temperature
    below: 70
  - platform: time_pattern
    hours: /01
  condition:
  - condition: template
    value_template: '{{ is_state(''script.frigidaire_climate_control_upstairs_power_toggle'',
      ''off'') and is_state(''script.lg_climate_control_upstairs_power_toggle'', ''off'')
      }}'
  action:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.bedroom_motion_sensor_temperature
        above: 75
      sequence:
      - service: script.frigidaire_climate_control_upstairs_power_toggle
      - service: script.lg_climate_control_upstairs_power_toggle
      - delay: 01:00:00
      - service: script.frigidaire_climate_control_upstairs_power_toggle
      - service: script.lg_climate_control_upstairs_power_toggle
    - conditions:
      - condition: numeric_state
        entity_id: sensor.bedroom_motion_sensor_temperature
        below: 70
      sequence:
      - service: script.frigidaire_climate_control_upstairs_power_toggle
      - service: script.lg_climate_control_upstairs_power_toggle
- id: '1710795370401'
  alias: Door Open TTS Alert
  description: Sends a TTS alert through selected speakers when the front or back
    door is opened, indicating which door was triggered.
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.back_door_contact
    id: back_door
    from:
    to: 'on'
  - platform: state
    entity_id:
    - binary_sensor.front_door_contact
    id: front_door
    from:
    to: 'on'
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: back_door
      sequence:
      - service: media_player.volume_set
        data:
          volume_level: 0.8
        target:
          entity_id:
          - media_player.kitchen_speaker
          - media_player.bedroom_speaker
      - service: tts.cloud_say
        data:
          message: Back door opened.
          entity_id: media_player.kitchen_speaker
      - service: tts.cloud_say
        data:
          message: Back door opened.
          entity_id: media_player.bedroom_speaker
    - conditions:
      - condition: trigger
        id: front_door
      sequence:
      - service: media_player.volume_set
        data:
          volume_level: 0.8
        target:
          entity_id:
          - media_player.kitchen_speaker
          - media_player.bedroom_speaker
      - service: tts.cloud_say
        data:
          entity_id: media_player.kitchen_speaker
          message: Front door opened.
      - service: tts.cloud_say
        data:
          message: Front Door opened.
          entity_id: media_player.bedroom_speaker
- id: '1710639809027'
  alias: Turn On Lights on Motion
  description: Turns on lights in various areas when no motion is detected, with room-specific
    delays.
  trigger:
  - platform: state
    entity_id: binary_sensor.bedroom_motion_sensor
    to: 'on'
    for: 00:00:{{ '%02d' | format(states('input_number.bedroom_motion_delay') | int)
      }}
    id: bedroom_motion
  - platform: state
    entity_id: binary_sensor.kitchen_motion_sensor
    to: 'on'
    for: 00:00:{{ '%02d' | format(states('input_number.kitchen_motion_delay') | int)
      }}
    id: kitchen_motion
  - platform: state
    entity_id: binary_sensor.media_room_motion_sensor
    to: 'on'
    for: 00:00:{{ '%02d' | format(states('input_number.media_room_motion_delay') |
      int) }}
    id: media_room_motion
  - platform: state
    entity_id: binary_sensor.stair_motion_sensor
    to: 'on'
    for: 00:00:{{ '%02d' | format(states('input_number.stairs_motion_delay') | int)
      }}
    id: stairs_motion
  - platform: state
    entity_id: binary_sensor.front_door_contact
    to: 'on'
    for: 00:00:{{ '%02d' | format(states('input_number.downstairs_motion_delay')|
      int) }}
    id: front_door_opened
  - platform: state
    entity_id: binary_sensor.back_door_contact
    to: 'on'
    for: 00:00:{{ '%02d' | format(states('input_number.downstairs_motion_delay')|
      int) }}
    id: back_door_opened
  condition:
  - condition: state
    entity_id: input_boolean.theme_mode
    state: 'off'
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: kitchen_motion
      sequence:
      - service: light.turn_on
        entity_id:
        - light.kitchen_overhead_1
        - light.kitchen_overhead_2
        - light.laundry_room_overhead_1
        - light.laundry_room_overhead_2
        data:
          brightness_pct: '{{ light_brightness }}'
          kelvin: '{{ light_kelvin }}'
    - conditions:
      - condition: trigger
        id: stairs_motion
      sequence:
      - service: light.turn_ON
        entity_id:
        - light.stairs_overhead_light
        - light.stairs_light_strip
        data:
          brightness_pct: '{{ light_brightness }}'
          kelvin: '{{ light_kelvin }}'
    - conditions:
      - condition: trigger
        id: bedroom_motion
      sequence:
      - choose:
        - conditions:
          - condition: state
            entity_id: input_boolean.someone_sleeping
            state: 'on'
          sequence:
          - service: light.turn_on
            entity_id:
            - light.bed_light_strip_1
            - light.bed_light_strip_2
            data:
              kelvin: '{{ light_kelvin }}'
              brightness_pct: 10
        default:
        - service: light.turn_on
          entity_id:
          - light.floorlamp
          - light.bedroom_overhead_light
          - light.bed_light_strip_1
          - light.bed_light_strip_2
          data:
            brightness_pct: '{{ light_brightness }}'
            kelvin: '{{ light_kelvin }}'
    - conditions:
      - condition: trigger
        id: media_room_motion
      sequence:
      - service: light.turn_ON
        entity_id:
        - light.media_room_overhead_light
        data:
          brightness_pct: '{{ light_brightness }}'
          kelvin: '{{ light_kelvin }}'
    - conditions:
      - condition: trigger
        id: front_door_opened
      sequence:
      - service: light.turn_on
        entity_id:
        - light.living_room_light
        - light.dining_room_light
        data:
          brightness_pct: '{{ light_brightness }}'
          kelvin: '{{ light_kelvin }}'
    - conditions:
      - condition: trigger
        id: back_door_opened
      sequence:
      - service: light.turn_ON
        entity_id:
        - light.kitchen_overhead_1
        - light.kitchen_overhead_2
        - light.laundry_room_overhead_1
        - light.laundry_room_overhead_2
        data:
          brightness_pct: '{{ light_brightness }}'
          kelvin: '{{ light_kelvin }}'
  variables:
    light_brightness: '{{ states(''input_number.home_light_brightness'') | int }}'
    light_color: '{{ states(''input_select.light_color'') }}'
    light_kelvin: '{{ states(''input_select.light_kelvin'') }}'
  mode: single
