- id: "1699583739347"
  alias: "Switch: Bedroom All Lights Off"
  description: Long Press Off Button
  trigger:
    - device_id: 3f330cd2e69e8ee831d5c5f0ab4bc433
      domain: hue
      platform: device
      type: long_press
      subtype: 4
      unique_id: 96d604ca-c2a4-4d4f-84f2-dbc6728ae2ae
    - device_id: c0fe949098f7ff63239d22535cf3240a
      domain: hue
      platform: device
      type: long_press
      subtype: 4
      unique_id: bce336b1-6bc2-4a46-bdd5-1c7bf7bbfd13
  condition: []
  action:
    - service: light.turn_off
      data: {}
      target:
        device_id:
          - 3e85e140da7932a78fa8c0c855488192
          - 0df99c2f064682cb887bdbc6004b11ff
          - 4f72c3af81e2dbfec9b42c8daa27bff6
          - 10bd54ec1321964b8f42513d95569fb1
          - ae9a7a6ecc1a78fb729248e254f52b32
          - e2863f42283465b7f5d3f51bdbf80ca2
          - 8fa0f75f077510dafcc4ba0cc5e02444
          - 73e277806daafc32a080362e8ac7d9be
          - 18b4a0379454cd85b2f18a962ffe8c30
          - 2fbfe2a1a69c726b59f2876e08c597f9
          - 04b3402eedc91e13a89c8d108bc7fd56
          - 4285466a8f1c5d3a42b2db310dff1f69
          - 303d1584166e2c7c7de70d806228e855
          - 1e2569baf7100aa8803bea93d7c70707
          - 7999bfaccf222410c3b9719e6c90c400
          - eae7a004eda9adfbfde9b48862d25977
          - adb799ad4a9a04501f78b0145d6dc3dd
  mode: single
- id: "1699583900858"
  alias: "Switch: Bedroom All Lights Lights On"
  description: Long Press On Button
  trigger:
    - device_id: 3f330cd2e69e8ee831d5c5f0ab4bc433
      domain: hue
      platform: device
      type: long_press
      subtype: 1
      unique_id: b21ca135-d892-465c-91f0-934426a4a5c9
  condition: []
  action:
    - service: light.turn_on
      data:
        transition: 60
        color_temp: 228
        brightness_pct: 100
      target:
        device_id:
          - 3e85e140da7932a78fa8c0c855488192
          - 0df99c2f064682cb887bdbc6004b11ff
          - 4f72c3af81e2dbfec9b42c8daa27bff6
          - 10bd54ec1321964b8f42513d95569fb1
          - ae9a7a6ecc1a78fb729248e254f52b32
          - e2863f42283465b7f5d3f51bdbf80ca2
          - 8fa0f75f077510dafcc4ba0cc5e02444
          - 73e277806daafc32a080362e8ac7d9be
          - 18b4a0379454cd85b2f18a962ffe8c30
          - 2fbfe2a1a69c726b59f2876e08c597f9
          - 04b3402eedc91e13a89c8d108bc7fd56
          - 4285466a8f1c5d3a42b2db310dff1f69
          - 303d1584166e2c7c7de70d806228e855
          - 1e2569baf7100aa8803bea93d7c70707
          - 7999bfaccf222410c3b9719e6c90c400
          - eae7a004eda9adfbfde9b48862d25977
          - adb799ad4a9a04501f78b0145d6dc3dd
  mode: single
- id: "1699584786811"
  alias: "Switch: Bedroom Lights On"
  description: Short Press On Button
  trigger:
    - device_id: 3f330cd2e69e8ee831d5c5f0ab4bc433
      domain: hue
      platform: device
      type: short_release
      subtype: 1
      unique_id: b21ca135-d892-465c-91f0-934426a4a5c9
  condition: []
  action:
    - service: light.turn_on
      data:
        transition: 5
        color_temp: 234
        brightness_pct: 100
      target:
        device_id:
          - 3e85e140da7932a78fa8c0c855488192
          - 0df99c2f064682cb887bdbc6004b11ff
          - 4f72c3af81e2dbfec9b42c8daa27bff6
          - 10bd54ec1321964b8f42513d95569fb1
          - e2863f42283465b7f5d3f51bdbf80ca2
          - 8fa0f75f077510dafcc4ba0cc5e02444
  mode: single
- id: "1699584906064"
  alias: "Switch: Bedroom Lights Off"
  description: Short Press Off Button
  trigger:
    - device_id: 3f330cd2e69e8ee831d5c5f0ab4bc433
      domain: hue
      platform: device
      type: short_release
      subtype: 4
      unique_id: 96d604ca-c2a4-4d4f-84f2-dbc6728ae2ae
  condition: []
  action:
    - service: light.turn_off
      data:
        transition: 5
      target:
        device_id:
          - 3e85e140da7932a78fa8c0c855488192
          - 0df99c2f064682cb887bdbc6004b11ff
          - 4f72c3af81e2dbfec9b42c8daa27bff6
          - 10bd54ec1321964b8f42513d95569fb1
          - e2863f42283465b7f5d3f51bdbf80ca2
          - 8fa0f75f077510dafcc4ba0cc5e02444
  mode: single
- id: "1699590281953"
  alias: "Switch: Downstairs Lights Off"
  description: Short Press Off Button
  trigger:
    - device_id: c0fe949098f7ff63239d22535cf3240a
      domain: hue
      platform: device
      type: short_release
      subtype: 4
      unique_id: bce336b1-6bc2-4a46-bdd5-1c7bf7bbfd13
  condition: []
  action:
    - service: light.turn_off
      data:
        transition: 5
      target:
        device_id:
          - ae9a7a6ecc1a78fb729248e254f52b32
          - 2fbfe2a1a69c726b59f2876e08c597f9
          - 04b3402eedc91e13a89c8d108bc7fd56
          - 1e2569baf7100aa8803bea93d7c70707
          - 4285466a8f1c5d3a42b2db310dff1f69
          - 303d1584166e2c7c7de70d806228e855
  mode: single
- id: "1699590566951"
  alias: "Switch: Downstairs Lights On"
  description: Short Press On Button
  trigger:
    - device_id: c0fe949098f7ff63239d22535cf3240a
      domain: hue
      platform: device
      type: short_release
      subtype: 1
      unique_id: 28d403aa-6339-4a1e-a63f-7f0e98dbccf0
  condition: []
  action:
    - service: light.turn_on
      data:
        color_temp: 412
        brightness_pct: 100
        transition: 15
      target:
        device_id:
          - ae9a7a6ecc1a78fb729248e254f52b32
          - 2fbfe2a1a69c726b59f2876e08c597f9
          - 04b3402eedc91e13a89c8d108bc7fd56
          - 4285466a8f1c5d3a42b2db310dff1f69
          - 303d1584166e2c7c7de70d806228e855
          - 1e2569baf7100aa8803bea93d7c70707
  mode: single
- id: "1699732340926"
  alias: Frigidare Power Toggle
  description: ""
  trigger:
    - platform: state
      entity_id:
        - input_boolean.frigidaire_ac_button
  condition: []
  action:
    - service: script.frigidaire_climate_control_upstairs_power_toggle
      data: {}
  mode: single
- id: "1699732652226"
  alias: LG AC Power Toggle
  description: ""
  trigger:
    - platform: state
      entity_id:
        - input_boolean.lg_ac_button
  condition: []
  action:
    - service: script.lg_climate_control_upstairs_power_toggle
      data: {}
  mode: single
- id: "1707603165027"
  alias: Play Clock Sound on the Hour and Half-Hour
  description: Plays a clock sound every hour and half-hour when the sun is up
  trigger:
    - platform: time_pattern
      minutes: "0"
    - platform: time_pattern
      minutes: "30"
  condition:
    - condition: state
      entity_id: sun.sun
      state: above_horizon
  action:
    - service: media_player.play_media
      target:
        entity_id: media_player.home
      data:
        media_content_id: media-source://media_source/local/antique-wood-chime-bell-ring.wav
        media_content_type: music
- id: "1709228035694"
  alias: Random Frog Chime During Daylight Hours
  description:
    Plays a random frog call every hour during daylight hours on randomly
    selected days.
  trigger:
    - platform: time_pattern
      hours: /1
      minutes: 0
      seconds: 0
  condition:
    - condition: state
      entity_id: sun.sun
      state: above_horizon
    - condition: state
      entity_id: input_boolean.play_frog_sounds_today
      state: "on"
  action:
    - variables:
        chosen_frog:
          "{{ ['https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2018/11/barking-treefrog-chorus.mp3',
          'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2018/11/bird-voiced-treefrog.mp3',
          'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2018/11/bronze-frog.mp3',
          'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2018/11/carpenter-frog.mp3',
          'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2020/11/southern-gray-treefrog-mating-call.mp3',
          'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2020/11/southern-gray-treefrog-rain-call.mp3',
          'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2018/11/narrow-mouthed-toad.mp3',
          'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2018/11/florida-gopher-frog.mp3',
          'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2018/11/green-treefrog.mp3',
          'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2018/11/green-treefrog-chorus.mp3',
          'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2018/11/green-treefrog-rain-call.mp3',
          'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2018/11/little-grass-frog.mp3',
          'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2018/11/little-grass-frog-rhythmic.mp3',
          'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2018/11/oak-toad-breeding-call.mp3',
          'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2018/11/ornate-chorus-frog.mp3',
          'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2018/11/pig-frog.mp3',
          'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2018/11/pinewoods-treefrog.mp3',
          'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2018/11/pinewoods-treefrog-chorus.mp3',
          'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2018/11/florida-chorus-frog.mp3',
          'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2018/11/southern-cricket-frog.mp3',
          'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2018/11/southern-cricket-frog-chorus.mp3',
          'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2018/11/southern-leopard-frog-chorus.mp3',
          'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2018/11/southern-toad-breeding-chorus.mp3',
          'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2018/11/spring-peeper.mp3',
          'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2020/11/spring-peeper-chorus-mating-call.mp3',
          'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2018/11/squirrel-treefrog.mp3',
          'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2018/11/squirrel-treefrog-chorus.mp3',
          'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2018/11/group-chorus-spring.mp3',
          'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2018/11/group-chorus-summer-july.mp3',
          'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2018/11/group-chorus-summer-august.mp3',
          'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2018/11/group-chorus-winter.mp3',
          'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/108/2020/10/Cuban-treefrog-calls_03.mp3'
          ][(range(0, 32) | random)] }}

          "
    - service: media_player.volume_set
      data:
        entity_id: media_player.bedroom_speaker
        volume_level: 0.8
    - service: media_player.play_media
      data_template:
        entity_id: media_player.bedroom_speaker
        media_content_id: "{{ chosen_frog }}"
        media_content_type: music
    - service: media_player.volume_set
      data:
        entity_id: media_player.kitchen_speaker
        volume_level: 0.8
    - service: media_player.play_media
      data_template:
        entity_id: media_player.kitchen_speaker
        media_content_id: "{{ chosen_frog }}"
        media_content_type: music
  mode: single
- id: "1709326067269"
  alias: Determine Daily Frog Sound Playback
  description:
    This automation will run the script just after midnight each day to
    randomly determine if the frog sounds should play that day.
  trigger:
    - platform: time
      at: 00:01:00
  action:
    - service: script.set_frog_sound_playback
