# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret server_address

automation: !include automations.yaml
recorder:
  db_url: !secret db_url

script: !include scripts.yaml

scene: !include scenes.yaml
