- platform: average
  name: "Average Weather Temperature"
  entities:
    - weather.forecast_home
    - weather.kvji_daynight
    - weather.openweathermap
- platform: average
  name: "Average Kitchen Temperature"
  entities:
    - sensor.kitchen_motion_sensor_temperature_measurement
  duration:
    hours: 3